// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, Client, TDataShape } from './client';
import type { GetUsersUsersGetData, GetUsersUsersGetResponses, CreateUsersUsersPostData, CreateUsersUsersPostResponses, CreateUsersUsersPostErrors } from './types.gen';
import { client } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get Users
 * Gets a list of all existing users, with their password. Enjoy Hackers!
 */
export const getUsersUsersGet = <ThrowOnError extends boolean = false>(options?: Options<GetUsersUsersGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetUsersUsersGetResponses, unknown, ThrowOnError>({
        url: '/users',
        ...options
    });
};

/**
 * Create Users
 */
export const createUsersUsersPost = <ThrowOnError extends boolean = false>(options: Options<CreateUsersUsersPostData, ThrowOnError>) => {
    return (options.client ?? client).post<CreateUsersUsersPostResponses, CreateUsersUsersPostErrors, ThrowOnError>({
        url: '/users',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};
