// This file is auto-generated by @hey-api/openapi-ts

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * User
 */
export type User = {
    /**
     * Name
     */
    name: string;
    /**
     * Email
     */
    email: string;
    /**
     * Id
     */
    id: number;
    /**
     * Password
     */
    password: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Confirm Password
     */
    confirm_password: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type GetUsersUsersGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users';
};

export type GetUsersUsersGetResponses = {
    /**
     * Response Get Users Users Get
     * Successful Response
     */
    200: Array<User>;
};

export type GetUsersUsersGetResponse = GetUsersUsersGetResponses[keyof GetUsersUsersGetResponses];

export type CreateUsersUsersPostData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/users';
};

export type CreateUsersUsersPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateUsersUsersPostError = CreateUsersUsersPostErrors[keyof CreateUsersUsersPostErrors];

export type CreateUsersUsersPostResponses = {
    /**
     * Successful Response
     */
    200: User;
};

export type CreateUsersUsersPostResponse = CreateUsersUsersPostResponses[keyof CreateUsersUsersPostResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};
